// Deploy helpers — shared utilities for the deploy-pass worker
// - slugify, exec, scp, ssh, DNS poll, TLS verify, compose-gen

import { exec } from 'node:child_process';
import { promises as fs } from 'node:fs';
import { resolve } from 'node:path';
import tls from 'node:tls';
import dns from 'node:dns';

const dnsResolve = dns.promises.resolve;

// --------------- slugify ---------------

/**
 * Convert a domain or business name into a safe URL/repo slug.
 * Lowercase, alphanumeric + hyphens only, max 63 chars, no leading/trailing hyphen.
 */
export function slugify(str) {
  let s = (str || 'untitled')
    .toLowerCase()
    .replace(/https?:\/\//g, '');         // strip protocol

  // If it looks like a domain (contains dots), take only the first label
  if (s.includes('.')) {
    s = s.split('.')[0];
  }

  s = s
    .replace(/[^a-z0-9-]/g, '-')          // replace non-slug chars with hyphen
    .replace(/-{2,}/g, '-')               // collapse consecutive hyphens
    .replace(/^-+|-+$/g, '')              // trim leading/trailing hyphens
    .slice(0, 63);                         // max length

  if (!s) s = 'untitled';
  // ensure starts with letter
  if (!/^[a-z]/.test(s)) s = 'site-' + s;
  return s;
}

// --------------- exec ---------------

/**
 * Execute a shell command, return { stdout, stderr }.
 * Throws on non-zero exit.
 */
export function execAsync(command, options = {}) {
  return new Promise((resolve, reject) => {
    exec(command, { timeout: options.timeout || 120_000, ...options }, (err, stdout, stderr) => {
      if (err) {
        const e = new Error(`Command failed: ${command}\n${stderr}`);
        e.code = err.code;
        e.stdout = stdout;
        e.stderr = stderr;
        reject(e);
      } else {
        resolve({ stdout: stdout.trim(), stderr: stderr.trim() });
      }
    });
  });
}

// --------------- SSH ---------------

const SSH_KEY = process.env.DH_DEPLOY_SSH_KEY || '/paperclip/instances/default/ssh/prin7r_vps_ed25519';
const SSH_HOST = process.env.DH_DEPLOY_SSH_HOST || 'root@144.91.94.91';
const SSH_OPTS = '-o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=15';

/**
 * Run a command on the remote server via SSH.
 */
export async function sshExec(command, options = {}) {
  const keyPath = options.sshKey || SSH_KEY;
  const host = options.sshHost || SSH_HOST;
  const sshCmd = `ssh -i ${keyPath} ${SSH_OPTS} ${host} ${escapeShell(command)}`;
  return execAsync(sshCmd, options);
}

/**
 * Copy a local file/directory to the remote server via scp.
 */
export async function scpUpload(localPath, remotePath, options = {}) {
  const keyPath = options.sshKey || SSH_KEY;
  const host = options.sshHost || SSH_HOST;
  const scpCmd = `scp -i ${keyPath} ${SSH_OPTS} -r ${escapeShell(localPath)} ${host}:${escapeShell(remotePath)}`;
  return execAsync(scpCmd, options);
}

/**
 * Quote a string for safe shell use — wraps in single quotes, escapes inner quotes.
 */
function escapeShell(str) {
  return `'${String(str).replace(/'/g, "'\\''")}'`;
}

// --------------- docker-compose generation ---------------

/**
 * Generate a docker-compose.yml string for a static site served by nginx + Traefik labels.
 */
export function generateComposeYaml({ slug, domain, port = 8080 }) {
  const domainRule = domain
    ? `Host(\`${domain}\`)`
    : `Host(\`${slug}.landing-pages-on-demand.prin7r.com\`)`;

  return `# Auto-generated by DropHouse deploy-pass — ${new Date().toISOString()}
services:
  web:
    image: nginx:alpine
    container_name: dh-${slug}
    restart: unless-stopped
    volumes:
      - ./site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "${port}"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dh-${slug}.rule=${domainRule}"
      - "traefik.http.routers.dh-${slug}.entrypoints=websecure"
      - "traefik.http.routers.dh-${slug}.tls.certresolver=letsencrypt"
      - "traefik.http.services.dh-${slug}.loadbalancer.server.port=${port}"

networks:
  traefik:
    external: true
`;
}

/**
 * Generate a minimal nginx.conf for static site serving.
 */
export function generateNginxConf() {
  return `server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Cache static assets
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # Security headers
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
`;
}

// --------------- DNS poll ---------------

/**
 * Poll DNS for an A or CNAME record pointing to the target.
 * Resolves every `intervalMs` for up to `maxWaitMs`.
 * Returns the resolved addresses or throws if timeout.
 */
export async function pollDns(domain, options = {}) {
  const maxWaitMs = options.maxWaitMs || 300_000;   // 5 min default
  const intervalMs = options.intervalMs || 15_000;
  const expectedIp = options.expectedIp || null;     // optional expected A record
  const expectedCname = options.expectedCname || null; // optional expected CNAME
  const start = Date.now();

  while (Date.now() - start < maxWaitMs) {
    try {
      // Try A record first
      const aRecords = await dnsResolve(domain, 'A');
      if (aRecords && aRecords.length > 0) {
        if (!expectedIp || aRecords.includes(expectedIp)) {
          return { type: 'A', addresses: aRecords };
        }
      }
    } catch {
      // No A record
    }

    try {
      // Try CNAME
      const cnameRecords = await dnsResolve(domain, 'CNAME');
      if (cnameRecords && cnameRecords.length > 0) {
        if (!expectedCname || cnameRecords.includes(expectedCname)) {
          return { type: 'CNAME', addresses: cnameRecords };
        }
      }
    } catch {
      // No CNAME record
    }

    // Wait before retry
    await new Promise(r => setTimeout(r, intervalMs));
  }

  throw new Error(`DNS poll timeout for ${domain} after ${maxWaitMs}ms`);
}

// --------------- TLS verify ---------------

/**
 * Verify TLS handshake against a host:port.
 * Returns certificate info or throws.
 */
export function verifyTls(host, port = 443, timeoutMs = 10_000) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      socket.destroy();
      reject(new Error(`TLS handshake timeout for ${host}:${port}`));
    }, timeoutMs);

    const socket = tls.connect({ host, port, servername: host, rejectUnauthorized: false }, () => {
      clearTimeout(timer);
      const cert = socket.getPeerCertificate();
      socket.end();
      resolve({
        authorized: socket.authorized,
        subject: cert.subject,
        issuer: cert.issuer,
        validFrom: cert.valid_from,
        validTo: cert.valid_to,
      });
    });

    socket.on('error', (err) => {
      clearTimeout(timer);
      reject(err);
    });
  });
}

// --------------- gh repo helpers ---------------

/**
 * Check if a GitHub repo exists.
 */
export async function ghRepoExists(orgRepo) {
  try {
    await execAsync(`gh repo view ${orgRepo} --json name`);
    return true;
  } catch {
    return false;
  }
}

/**
 * Create a GitHub repo from a local directory and push.
 */
export async function ghRepoCreate(orgRepo, sourcePath, options = {}) {
  const description = options.description || 'Generated by DropHouse';
  const cmd = `gh repo create ${orgRepo} --public --source=${escapeShell(sourcePath)} --push --description=${escapeShell(description)}`;
  return execAsync(cmd, options);
}
